### ISSUE TITLE
Exception in Play 2.6.0-RC2

### ISSUE THREAD

**Issue by lukaszwierzynskidh** [eclipsesource/play-json-schema-validator#118]
Library doesn't work since Scla Play 2.6.0-RC2. 

`[RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsArray.value()Lscala/collection/Seq;]`

full stack trace:
`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsArray.value()Lscala/collection/Seq;]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:257)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:184)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:228)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:227)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsArray.value()Lscala/collection/Seq;
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:424)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:211)
	at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:275)
Caused by: java.lang.NoSuchMethodError: play.api.libs.json.JsArray.value()Lscala/collection/Seq;
	at com.eclipsesource.schema.internal.validators.ArrayValidator$.validate(ArrayValidator.scala:17)
	at com.eclipsesource.schema.internal.validators.ArrayValidator$.validate(ArrayValidator.scala:13)
	at com.eclipsesource.schema.package$SchemaTypeExtensionOps.validateConstraints(package.scala:137)
	at com.eclipsesource.schema.package$SchemaTypeExtensionOps.validate(package.scala:102)
	at com.eclipsesource.schema.internal.validators.ObjectValidator$.$anonfun$validateProps$3(ObjectValidator.scala:57)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at com.eclipsesource.schema.internal.validators.ObjectValidator$.$anonfun$validateProps$1(ObjectValidator.scala:43)
	at scalaz.package$ReaderWriterState$.$anonfun$apply$3(package.scala:189)`

**Comment by edgarmueller** [comment]
Thanks for the report! Yes, I think there was binary incompatible change in Play JSON with RC2, I'll update the dependencies over the weekend.

**Comment by edgarmueller** [comment]
Fixed with 0.9.2

**Comment by lukaszwierzynskidh** [comment]
thanks a lot!
