### ISSUE TITLE
issue when building using sbt

### ISSUE THREAD

**Issue by jcaicedo99** [eclipsesource/play-json-schema-validator#74]
Hello master ,

I found this code very interesting, but hit this issue trying to run sbt console.

home\.bintray\.credentials

I created an empty file however it is expecting .credentials with additional information in a particular format. Could you please provide an example or valid .credentials file ?

Thanks

C:\MyProject\play-json-schema-validator-master>sbt console
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\MyProject\play-json-schema-validator-master\project
bintray credentials missing credential properties realm, host, user, password in C:\Users\john\.bintray\.credentials is malformed
java.lang.RuntimeException: missing credential properties realm, host, user, password in C:\Users\john\.bintray\.credentials
        at scala.sys.package$.error(package.scala:27)
        at bintray.Bintray$$anonfun$ensuredCredentials$1.apply(Bintray.scala:60)
        at bintray.Bintray$$anonfun$ensuredCredentials$1.apply(Bintray.scala:60)
        at scala.util.Either.fold(Either.scala:97)
        at bintray.Bintray$.ensuredCredentials(Bintray.scala:60)
        at bintray.Bintray$.withRepo(Bintray.scala:49)
        at bintray.BintrayPlugin$$anonfun$publishToBintray$1.apply(BintrayPlugin.scala:180)
        at bintray.BintrayPlugin$$anonfun$publishToBintray$1.apply(BintrayPlugin.scala:175)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] missing credential properties realm, host, user, password in C:\Users\john\.bintray\.credentials
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

**Comment by edgarmueller** [comment]
You don't need the .credentials file, since that file is only used when creating a release. Furthermore, it's only a warning which you may safely ignore. So, just delete your .credentials file and you should be good.
